/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    HomeLayout: typeof import('./src/components/Layout/HomeLayout.vue')['default']
    InputBox: typeof import('./src/components/ChatBox/InputBox.vue')['default']
    MessageItem: typeof import('./src/components/ChatBox/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/ChatBox/MessageList.vue')['default']
    PrimaryHeader: typeof import('./src/components/Layout/PrimaryHeader.vue')['default']
    PrimarySider: typeof import('./src/components/Layout/PrimarySider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
