/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatItem: typeof import('./src/components/Layout/Sider/ChatItem.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    GroupItem: typeof import('./src/components/Layout/Sider/GroupItem.vue')['default']
    InputBox: typeof import('./src/components/ChatBox/InputBox.vue')['default']
    MemberItem: typeof import('./src/components/ChatBox/MemberItem.vue')['default']
    MemberList: typeof import('./src/components/ChatBox/MemberList.vue')['default']
    MessageItem: typeof import('./src/components/ChatBox/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/ChatBox/MessageList.vue')['default']
    PrimaryHeader: typeof import('./src/components/Layout/Header/PrimaryHeader.vue')['default']
    PrimarySider: typeof import('./src/components/Layout/Sider/PrimarySider.vue')['default']
    RoomList: typeof import('./src/components/Layout/Sider/RoomList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
