/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatItem: typeof import('./src/components/Layout/Sider/ChatItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    GroupItem: typeof import('./src/components/Layout/Sider/GroupItem.vue')['default']
    InputBox: typeof import('./src/components/ChatBox/InputBox.vue')['default']
    MemberItem: typeof import('./src/components/ChatBox/MemberItem.vue')['default']
    MemberList: typeof import('./src/components/ChatBox/MemberList.vue')['default']
    MessageItem: typeof import('./src/components/ChatBox/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/ChatBox/MessageList.vue')['default']
    PrimaryHeader: typeof import('./src/components/Layout/Header/PrimaryHeader.vue')['default']
    PrimarySider: typeof import('./src/components/Layout/Sider/PrimarySider.vue')['default']
    RoleItem: typeof import('./src/components/Layout/Sider/RoleItem.vue')['default']
    RoleList: typeof import('./src/components/Layout/Sider/RoleList.vue')['default']
    RoomList: typeof import('./src/components/Layout/Sider/RoomList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
