export enum InstructionEnum {
  UNKNOWN = 1,
  DICE = 2,
  CHECK = 3
}

export const propertyToChineseMap = new Map([
  ['roleId', '角色ID'],
  ['strength', '力量'],
  ['dexterity', '敏捷'],
  ['willpower', '意志力'],
  ['constitution', '体质'],
  ['appearance', '外貌'],
  ['education', '教育程度'],
  ['size', '体型'],
  ['intelligence', '智力'],
  ['sanity', '理智'],
  ['luck', '运气'],
  ['magicPoints', '魔法点数'],
  ['healthPoints', '生命值'],
  ['accounting', '会计学'],
  ['anthropology', '人类学'],
  ['appraisal', '鉴定'],
  ['archaeology', '考古学'],
  ['acting', '表演'],
  ['charm', '魅力'],
  ['climb', '攀爬'],
  ['computerUse', '计算机使用'],
  ['creditRating', '信用评级'],
  ['cthulhuMythos', '克苏鲁神话'],
  ['disguise', '伪装'],
  ['dodge', '闪避'],
  ['drive', '驾驶'],
  ['electricRepair', '电器维修'],
  ['electronics', '电子学'],
  ['fastTalk', '花言巧语'],
  ['fistfight', '拳击'],
  ['firearms', '火器使用'],
  ['firstAid', '急救'],
  ['history', '历史'],
  ['intimidate', '恐吓'],
  ['jump', '跳跃'],
  ['english', '英语'],
  ['russian', '俄语'],
  ['law', '法律'],
  ['libraryUse', '图书馆使用'],
  ['listen', '聆听'],
  ['locksmith', '开锁'],
  ['machineRepair', '机械维修'],
  ['medicine', '医学'],
  ['naturalWorld', '自然界知识'],
  ['navigation', '导航'],
  ['occult', '神秘学'],
  ['persuade', '说服'],
  ['psychology', '心理学'],
  ['ride', '骑乘'],
  ['pharmacy', '药学'],
  ['sleightOfHand', '巧手'],
  ['investigation', '调查'],
  ['stealth', '潜行'],
  ['survival', '生存'],
  ['swim', '游泳'],
  ['throwAbility', '投掷能力'],
  ['track', '追踪'],
  ['animalTraining', '动物训练'],
  ['demolition', '爆破'],
  ['lipReading', '唇语解读'],
  ['hypnosis', '催眠'],
  ['artillery', '火炮使用']
])
